### ISSUE TITLE
Which IP to connect?

### ISSUE THREAD

**Issue by Tvvgge** [Traeger-GmbH/sinumeriknet-samples#3]
Hi, do anybody know what's the correct IP to connect? I'm using 840d sl with ethernet cable connected from X127 port to my laptop. And  then I typed in the X127 IP address to this command "using (var client = new SinumerikClient("s840d.sl://192.168.215.1"))" what I replaced 192.168.0.80 to 192.168.215.1, but when I run the code I can't get the value from my cnc machine. Do anybody know what's the problem? Should I modify the 840d via 840d toolbox?
All I did is open the file"SinumerikNet.Advanced.Samples.sln" and change the IP and then run the code
Since I'm new to C# so I don't really know if I did it wrong.
Thank you in advance!!

**Comment by dscharnagl** [comment]
Hi Tvvgge,

thank you for your interest into our SDK. If the IP address entered in the sample matches the one configured for the X127 port you shall be able to connect to the controller. However you can check this in TIA portal or the HMI connected to the Sinumerik as well.

If this does not solve the issue: Please provide more details like screenshots of an exception or the general outcome of the code modified / executed.

Kind regards

**Comment by Tvvgge** [comment]
Hello dscharnagl,

thanks for your response! Below is my CNC version, IP, and the result of running the code "Position". There is no error or any issue. But the outcome window shows nothing. I tried code "Data" and "Events" but they showed nothing as well. I read the manual "IP S7 LINK SDK for .NET" which is for SIMATIC-S7 series from your website. And it says "To use the SDK, various settings must be made on the PLC.". I'm not sure if I have to do the same to my 840d NCU? 
thank you.

![IMG_8154](https://user-images.githubusercontent.com/85278709/159464413-86ddc97c-12c9-4df7-b4df-f5641bb11c3c.jpg)
![IMG_8206](https://user-images.githubusercontent.com/85278709/159465252-9395cd9e-7be0-4957-a5dc-a66d4605e526.jpg)
![runing the code](https://user-images.githubusercontent.com/85278709/159464643-5803ab7a-caaa-4d3c-8fd7-f4ff111b4530.PNG)

**Comment by dscharnagl** [comment]
Hello Tvvgge,

thank you for sharing the screenshots. According to the information supplied I'd expect that everything shall work. However we've just recognized that the package references in the sample projects were  outdated. I've updated the package references to the latest version.

Please give the updated projects another try. If this does still not solve the issue: Please respond accordingly.

Kind regards

**Comment by flaviopaulofp** [comment]
hello tvgge,

Siemens does not recommend changing the IP of the x127 port.
It was able to read the values through the x130 port recommended for this type of application.


I'll perform a test on the x127 port, and I'll report the result.

Below are screenshots of the script that worked.


![Script](https://user-images.githubusercontent.com/56745239/159525703-11bfa91d-a545-4449-a699-2d363a3bb607.png)

**Comment by flaviopaulofp** [comment]
I performed the test through the x127 port and it also worked
![image](https://user-images.githubusercontent.com/56745239/159542661-5838d697-4cca-4572-8e28-92f232ffb5d1.png)

After changing scharnagl it also works

![image](https://user-images.githubusercontent.com/56745239/159543352-88b4200e-9f04-496c-b3b1-6e1bff311f3f.png)

thank you!

**Comment by Tvvgge** [comment]
Hello @dscharnagl and @flaviopaulofp,

Thanks to your help!! 

I tried the latest update of the project and now I'm having this problem:
![001](https://user-images.githubusercontent.com/85278709/159616526-9361ac00-1401-48c2-bade-40df01a611d2.PNG)
![002](https://user-images.githubusercontent.com/85278709/159616533-f39679df-4739-49fd-9151-e12a4ea9cb47.PNG)

It says "The connection is in 'Faulted' state.". I don't know if this means it doesn't connect to the 840d. I use the IP from X130 port. And I can ping the IP through cmd. So I don't think it's connection problem. But I don't really know what's the issue means. I google the error, but the search results are all about WCF... I used Visual Studio 2017 and 2022, they both have the problem.

By the way, I used the old project yesterday. The problem I had was there was no error in my code but the output window showed nothing. Interestingly, when I used a wrong IP, the code could still run without error. And the output window showed nothing as well. So does it means that it just cannot connected to 840d even if I use the right IP?

I tried the first code @flaviopaulofp post and another problem shows up, the detail is 
\---------------------------------------------------------------------------------------------------------------------------------\
Sinumerik.Advanced.NckException
  HResult=0x80131500
  Message=The status is unspecified and is therefore unknown (code=-1).
 Reason: 無法載入檔案或組件 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' 或其相依性的其中之一。 系統找不到指定的檔案。
  Source=SinumerikNet.Advanced
  StackTrace:
   at Sinumerik.Advanced.NckException.a(Exception a)
   at Sinumerik.Advanced.NckDeviceConnection.Open()
   at Data.Program.Main() in C:\Users\jusda\Downloads\sinumeriknet-samples-master (1)\sinumeriknet-samples-master\cs\Basic\Data\Program.cs:line 22

Inner Exception 1:
FileNotFoundException: 無法載入檔案或組件 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' 或其相依性的其中之一。 系統找不到指定的檔案。
\---------------------------------------------------------------------------------------------------------------------------------\
It seems that the system cannot find the corresponding file.
![003](https://user-images.githubusercontent.com/85278709/159617993-38d43e43-45c4-47b7-ac63-6cf358df5fe9.PNG)

I was using the 840d OPC UA server and Node-Red OPC UA client to collect data from 840d. But the OPC UA server's sampling interval is too rough, that caused my data loss(for example the data should be 1,2,3,4,5,6,7,8,9, but I only get 1,3,4,5,7,8). So I'm looking for a solution which has smaller sampling interval.
Anyway, thanks to your help!  You guys are so kind!!

**Comment by Tvvgge** [comment]
Is there something I have to do beforehand? Like disable the firewall or Modify the 840d and build a connection between 840d and my laptop through sinumerik 840d toolbox? Or I can literally just connect the x130/x127 port with ethernet port on the laptop and change the IP on the code then everything would work?

**Comment by flaviopaulofp** [comment]
Hello Tvvgge,

I believe that the toolbox 840d is not necessary, but perhaps the activation of the Firewall. These settings are only needed for port x130, ports x127 and x120 are already released.

![image](https://user-images.githubusercontent.com/56745239/159688902-37210a13-1bf3-404d-9f5d-c76a026ad9c3.png)

I had the same problem as you when using the code posted by dscharnagl, I don't know where the problem may be, but I solved it as follows.

![image](https://user-images.githubusercontent.com/56745239/159689088-1c1f3b16-366b-44c0-89d3-043501258420.png)


1º I created a new solution
 
2º Copy the code from dscharnagl
![image](https://user-images.githubusercontent.com/56745239/159689251-9792f011-32a6-4a7f-bec8-1499f0141cb5.png)


3º Installed the NUGET Package (SinumerikNet.Advanced) Tools>Nuget Package manager>Manager Nuget Package for Solution

![image](https://user-images.githubusercontent.com/56745239/159689675-afbbbb03-1420-4ff4-a14a-f3d20311228d.png)


Result

![image](https://user-images.githubusercontent.com/56745239/159689928-cef59452-fc17-4960-bd85-76df209b1b12.png)

Thank you!

**Comment by flaviopaulofp** [comment]
Tvvgge, do you have any reference how to use 840d OPC UA server to send me?

**Comment by flaviopaulofp** [comment]
@dscharnagl knows what could be going wrong in the last code you posted?

**Comment by Tvvgge** [comment]
@flaviopaulofp thanks for your detailed instruction!! 

I follow your step and the error is gone. Now I'm having another error that says "No connection could be made because the target machine actively refused it.". I think it's a good thing since my CNC is closed right now, so I use the IP from another device. And it finally shows me something about connection error instead of running without error. I will try to connect the 840d once I get access to the machine. Thank you so much!!

These are the documents about the 840d OPC UA server I have
Instruction of setting up the OPC UA server: [840Dsl_828D_OPCUA_config_man_1218_en-US.pdf](https://github.com/Traeger-GmbH/sinumeriknet-samples/files/8332940/840Dsl_828D_OPCUA_config_man_1218_en-US.pdf)
NC variables for data acquisition or machine control: [840Dsl_NC_variables.pdf](https://github.com/Traeger-GmbH/sinumeriknet-samples/files/8332944/840Dsl_NC_variables.pdf)

Thank you!!

**Comment by flaviopaulofp** [comment]
@Tvvgge Thank you for the informations!

When you have access to the machine, tell us how the connection was.

Thank you!!

**Comment by kpreisser** [comment]
Hi @Tvvgge and @flaviopaulofp,
thank you for your feedback!

The errors `The connection is in 'Faulted' state.` as well as the `FileLoadException` were caused by msising dependencies in our [NuGet package](https://www.nuget.org/packages/SinumerikNet.Advanced) for `net46` and `netstandard2.0`,  and our sample projects run by default with .NET Framework 4.6. We have fixed this in the next version of `SinumerikNet.Advanced`, where these errors should no longer occur.

As a workaround until the new version is released, when running for .NET Framework, you can add these two dependencies in your `.csproj`:
```xml
<ItemGroup>
  <PackageReference Include="System.Memory" Version="4.5.4" />
  <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
</ItemGroup>
```

These exceptions don't occur when running with .NET Core 3.1 or higher, which is probably why it worked when you have created a new project (in case you have created a .NET Core/.NET 5/.NET 6 project).
Alternatively, you can also select a different target framework when running our sample projects in Visual Studio:
![grafik](https://user-images.githubusercontent.com/13289184/159702923-226f00af-d396-402d-a53d-3c671e1ee7d5.png)

**Comment by Tvvgge** [comment]
Hello @flaviopaulofp and @kpreisser,

I tried your method and it works!!! Thanks for all your assistance. Without you guys I cannot achieve it by myself😭 I really appreciate your help!
![nice](https://user-images.githubusercontent.com/85278709/159822488-f18e318b-6300-4290-b9da-847f5418bf29.PNG)

**Comment by flaviopaulofp** [comment]
> PackageReference Include = " System.Memory " Version = " 4.5.4 " /> < PackageReference Include = " System.Threading.Tasks.Extensions " Version = " 4.5.4 " />


@kpreisser your method worked!

Thanks!

**Comment by flaviopaulofp** [comment]
> Olá @flaviopaulofp e @kpreisser ,
> 
> Testei seu método e funcionou!!! Obrigado por toda sua ajuda. Sem vocês eu não posso conseguir isso sozinho😭Eu realmente aprecio sua ajuda! ![legais](https://user-images.githubusercontent.com/85278709/159822488-f18e318b-6300-4290-b9da-847f5418bf29.PNG)

Congratulations!
